backend/backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from coreapi.views import index

urlpatterns = [
    path('',include('coreapi.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/',include('connection.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/coreapi/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm
app_name='coreapi'

urlpatterns=[
    path('',views.index,name='index'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='coreapi/login.html',authentication_form=LoginForm),name='login'),
]

backend/item/urls.py
from django.urls import path
from . import views


app_name='item'

urlpatterns = [
    path('',views.items,name='items'),
    path('new/',views.new,name='new'),
    path('<int:pk>/',views.detail,name='detail'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/',views.edit,name='edit'),
]

backend/coreapi/models.py
from django.db import models

backend/coreapi/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']

    username=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'typeusername'
    }))

    email=forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'email'
    }))

    password1=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'password'
    }))

    password2=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'confirm password'
    }))

class LoginForm(AuthenticationForm):
    username=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'typeusername'
    }))
    password=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'password'
    }))

backend/coreapi/views.py
from django.shortcuts import render,redirect
from item.models import Category,Item
from django.shortcuts import get_object_or_404
from .forms import SignupForm



def index(request):
    items=Item.objects.filter(is_sold=False)[0:6]
    catagories=Category.objects.all()
    return render(request,'coreapi/index.html',{   
        'catagories':catagories,
        'items':items,
    })
def contact(request):
    return render(request,'coreapi/contact.html')

def signup(request):
    if request.method=='POST':
        form=SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login')
    else:
        form=SignupForm
    return render(request,'coreapi/signup.html',{
        'form':form
    })

backend/coreapi/templates/coreapi/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav>{% block nav %}nav{% endblock %}</nav>
    <div>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

backend/coreapi/templates/coreapi/contact.html
{%extends 'coreapi/base.html'%} 

{% block title %}contact{% endblock %}

{%block content%}
<h1>contact</h1>
{%endblock%}

backend/coreapi/templates/coreapi/index.html
{%extends 'coreapi/base.html'%} {% block title %}welcome{% endblock %} 

{%block content%}
<div>
  <h2>items</h2>
  <div>
    {%for item in items%}
    <div>
      <a href="{% url 'item:detail' item.id %}">
        <div>
          <img src="{{item.image.url}}" alt="" style="width: 100px" />
        </div>
        <div>
          <h2>{{item.name}}</h2>
          <p>Price: {{item.price}}</p>
        </div>
      </a>
      {%endfor%}
    </div>
  </div>

  <div>
    <h2>catagory</h2>
    <div>
      {%for catagory in catagories%}
      <div>
        <a href="">
          <div>
            <h2>{{catagory.name}}</h2>
            <p>{{ catagory.items.count }} items</p>
          </div>
        </a>
      </div>
      {%endfor%}
    </div>
  </div>
</div>
{%endblock%}

backend/coreapi/templates/coreapi/login.html
{%extends 'coreapi/base.html'%}
 {%block title%}log in{%endblock%} 
 {%block content%}
<div>
  <h1>login</h1>

  <form method="post" action="">
    {% csrf_token %}
    <div><label for="">username</label>{{form.username}}</div>
    <div><label for="">password</label>{{form.password}}</div>
   

    {% if form.errors or form.non_field_errors %}
    <div>
        {% for field in form %}
           {{ field.errors }}
        {%endfor%}


        {{form.non_field_errors}}
    </div>
    {% endif %}

    <button>submit</button>
  </form>
</div>

{%endblock%}

backend/coreapi/templates/coreapi/signup.html
{%extends 'coreapi/base.html'%} {%block title%}signup{%endblock%} {%block content%}
<div>
  <h1>signup</h1>

  <form method="post" action="">
    {% csrf_token %}
    <div><label for="">username</label>{{form.username}}</div>
    <div><label for="">email</label>{{form.email}}</div>
    <div><label for="">password</label>{{form.password1}}</div>
    <div><label for="">confirm password</label>{{form.password2}}</div>

    {% if form.errors or form.non_field_errors %}
    <div>
        {% for field in form %}
           {{ field.errors }}
        {%endfor%}


        {{form.non_field_errors}}
    </div>
    {% endif %}

    <button>submit</button>
  </form>
</div>

{%endblock%}